
import { Lesson } from './types';

export const KEYBOARD_ROWS = [
  ['`', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', 'Backspace'],
  ['Tab', 'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '[', ']', '\\'],
  ['Caps', 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', ';', "'", 'Enter'],
  ['Shift', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', ',', '.', '/', 'Shift'],
  ['Space']
];

const generateStandardLessons = (): Lesson[] => {
  const commonWords = [
    "the quick brown fox jumps over the lazy dog",
    "practice makes perfect when learning to type",
    "a journey of a thousand miles begins with a single step",
    "to be or not to be that is the question",
    "all that glitters is not gold",
    "consistency is the key to mastering any new skill",
    "typing speed will improve with daily deliberate practice",
    "focus on accuracy first then speed will follow naturally",
    "rhythm and flow are essential for high speed typing",
    "never look down at your hands while typing",
    "use all ten fingers for maximum efficiency",
    "the home row is your base of operations",
    "keep your wrists elevated and back straight",
    "take frequent breaks to avoid repetitive strain",
    "mechanical keyboards provide excellent tactile feedback",
    "typing is a fundamental skill in the digital age",
    "software engineers spend hours typing code every day",
    "writers find their flow through the clicking of keys",
    "the sound of a busy office is often the sound of typing",
    "digital nomads work from anywhere with their laptops",
    "high speed internet has changed the world forever",
    "artificial intelligence is transforming our lives",
    "machine learning models require massive amounts of data",
    "quantum computing represents the next frontier",
    "blockchain technology enables decentralized systems",
    "cybersecurity is a critical concern for businesses",
    "cloud computing provides scalable infrastructure",
    "data science helps us make better decisions",
    "user experience design focuses on the human element",
    "agile methodologies improve software development cycles",
    "open source software encourages collaboration",
    "web development involves html css and javascript",
    "mobile apps are ubiquitous in modern society",
    "social media connects people across the globe",
    "e-commerce has revolutionized the way we shop",
    "virtual reality creates immersive digital experiences",
    "augmented reality overlays data on the real world",
    "the internet of things connects physical devices",
    "big data analytics reveals hidden patterns",
    "fintech innovations are changing banking",
    "edtech platforms provide accessible learning",
    "healthtech improves patient outcomes with data",
    "clean energy is essential for a sustainable future",
    "space exploration continues to inspire humanity",
    "robotics automates complex and dangerous tasks",
    "biotechnology advances our understanding of life",
    "nanotechnology operates at the scale of atoms",
    "autonomous vehicles will redefine transportation",
    "smart cities use data to improve urban living",
    "digital privacy is a fundamental human right"
  ];

  return commonWords.map((text, i) => ({
    id: `s-${i}`,
    title: `Standard Exercise ${i + 1}`,
    difficulty: i < 20 ? 'Beginner' : i < 40 ? 'Intermediate' : 'Advanced',
    category: 'Standard',
    description: 'General purpose typing practice.',
    text
  }));
};

const generateCodingLessons = (): Lesson[] => {
  const snippets = [
    // JavaScript - Core & ES6+
    "console.log('Hello, JavaScript!');",
    "const sum = (a, b) => a + b;",
    "for (let i = 0; i < 10; i++) { console.log(`Index: ${i}`); }",
    "const filtered = items.filter(item => item.id !== currentId);",
    "const [data, setData] = useState({ loading: true, payload: null });",
    "const { value, onChange } = useFormField('initial');",
    "const memoizedValue = useMemo(() => compute(a, b), [a, b]);",
    "const handler = useCallback((event) => { event.preventDefault(); }, []);",
    "export default function Component({ children, className }) { return <div className={className}>{children}</div>; }",
    "const response = await fetch('/api/v1/users', { method: 'POST', body: JSON.stringify(payload) });",
    "const data = await response.json(); console.table(data);",
    "const updated = { ...state, items: [...state.items, newItem] };",
    "import { createSlice, configureStore } from '@reduxjs/toolkit';",
    "const authSlice = createSlice({ name: 'auth', initialState, reducers: { login: (s, a) => { s.user = a.payload; } } });",
    "window.addEventListener('scroll', throttle(() => console.log('scrolling'), 100));",
    "const config = Object.freeze({ baseURL: process.env.API_URL, timeout: 5000 });",
    "function* idGenerator() { let i = 0; while(true) { yield i++; } }",
    "const observer = new IntersectionObserver((entries) => { entries.forEach(e => e.isIntersecting); });",
    "localStorage.setItem('theme', isDark ? 'dark' : 'light');",
    "const params = new URLSearchParams(window.location.search);",
    "const debounced = _.debounce(searchHandler, 300);",
    "const pipeline = (...fns) => x => fns.reduce((v, f) => f(v), x);",
    "type DeepPartial<T> = { [P in keyof T]?: DeepPartial<T[P]> };",
    "interface UserProfile extends BaseEntity { email: string; avatarUrl?: string; }",
    "enum Status { Pending = 'PENDING', Success = 'SUCCESS', Error = 'ERROR' }",
    "const isString = (val: unknown): val is string => typeof val === 'string';",
    "const result = await Promise.allSettled([req1, req2, req3]);",
    "const symbolKey = Symbol('private'); obj[symbolKey] = true;",
    "const proxy = new Proxy(target, { get: (t, prop) => t[prop] });",
    "Reflect.has(obj, 'key'); Reflect.ownKeys(obj);",

    // Python - Core & Logic
    "print('Hello, Pythonic World!')",
    "def calculate_total(prices: list[float]) -> float: return sum(prices)",
    "if __name__ == '__main__': main()",
    "class User(BaseModel): id: int; username: str; email: EmailStr",
    "squares = [x**2 for x in range(10) if x % 2 == 0]",
    "user_map = {u.id: u.username for u in users if u.is_active}",
    "async def get_details(user_id: str): return await db.fetch_one(query, values={'id': user_id})",
    "with open('config.yaml', 'r') as f: config = yaml.safe_load(f)",
    "import pandas as pd; df = pd.read_csv('data.csv'); print(df.groupby('category').mean())",
    "import numpy as np; a = np.linspace(0, 10, 100); b = np.sin(a)",
    "from typing import List, Optional, Union, Dict",
    "def process_data(data: Union[List[int], Dict[str, int]]) -> Optional[int]: return None",
    "lambda x, y: x if x > y else y",
    "def log_decorator(func): def wrapper(*args, **kwargs): return func(*args, **kwargs); return wrapper",
    "@app.get('/items/{item_id}') async def read_item(item_id: int): return {'id': item_id}",
    "class Singleton: _instance = None; def __new__(cls): if not cls._instance: ...",
    "import requests; res = requests.get('https://api.github.com', timeout=5)",
    "try: value = data['key'] except KeyError as e: value = None",
    "import os; api_key = os.getenv('API_KEY', 'default_secret')",
    "for index, value in enumerate(items): print(f'{index}: {value}')",
    "list(filter(lambda x: x > 0, numbers))",
    "any(x.is_valid for x in processes)",
    "itertools.chain(list_a, list_b)",
    "collections.defaultdict(list)",
    "import json; data = json.loads(raw_string)",
    "df.dropna(subset=['id']).reset_index(drop=True)",
    "plt.plot(x, y, label='Accuracy'); plt.legend(); plt.show()",
    "X_train, X_test = train_test_split(df, test_size=0.2)",
    "model.add(layers.Dense(64, activation='relu', input_shape=(10,)))",
    "optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)",
    "import fastapi; app = fastapi.FastAPI()",
    "from sqlalchemy import Column, Integer, String; class User(Base): ...",
    "django.contrib.admin.site.register(MyModel)",
    "with sqlite3.connect('db.sqlite') as conn: cursor = conn.cursor()",
    "os.path.join(base_dir, 'static', 'css', 'main.css')",
    "glob.glob('*.png')",
    "re.match(r'^[a-zA-Z0-9]+$', test_string)",
    "time.sleep(2.5)",
    "threading.Thread(target=worker_func).start()",
    "multiprocessing.Pool(processes=4).map(job, tasks)",
    "logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')",

    // Web & Tools
    "npm run dev -- --port 3000",
    "git checkout -b feature/new-auth-flow",
    "docker-compose build --no-cache && docker-compose up",
    "kubectl get deployments -n prod --watch",
    "SELECT COUNT(*) FROM orders WHERE status = 'shipped';",
    "UPDATE users SET last_login = NOW() WHERE id = $1;",
    "INSERT INTO products (sku, price) VALUES ('A100', 49.99);",
    "chmod 755 script.sh && ./script.sh",
    "cat error.log | grep -i 'exception' | tail -n 20",
    "curl -i -H 'Accept: application/json' http://localhost:8000",
    "ssh -i ~/.ssh/id_rsa ec2-user@api.example.com",
    "aws s3 sync ./dist s3://my-bucket-name",
    "firebase deploy --only hosting:production",
    "terraform apply -var-file='prod.tfvars' -auto-approve",

    // Advanced Keyboard Challenges (Heavy Symbols)
    "{ [ ( ) ] } -> => && || ! ? : ; . , / \\ | ' \" `",
    "const { a, b } = { a: [1, 2], b: (x) => x * x };",
    "for (let i = 0; i < n; i++) { if (arr[i] === target) return i; }",
    "def func(*args, **kwargs): return f'Args: {args}, Kwargs: {kwargs}'",
    "((x && y) || (!z)) ? true : false;",
    "[ ...Array(10).keys() ].map(n => n % 2 ? 'odd' : 'even');",
    "regex = /^[a-z]+@[a-z]+\\.[a-z]{2,3}$/i;",
    "await Promise.all([ fetch(u1), fetch(u2) ]).catch(e => log(e));",
    "data = { 'a': 1, 'b': { 'c': 2 } }; val = data.get('b', {}).get('c')",
    "import { x as y } from './mod'; export { y };",
    "const fn = (x: T): Promise<U> => new Promise((res) => { ... });",
    "a[i][j] = b[k++]; c[--m] = d[n++];",
    "git rebase -i HEAD~3",
    "ssh-keygen -t ed25519 -C 'user@domain.com'",
    "npm i -D @types/react @types/react-dom @types/jest",
    "sudo systemctl restart nginx.service",
    "python3 -m venv .venv && source .venv/bin/activate",
    "pip install -r requirements.txt",
    "pytest -v -s ./tests",
    "coverage run -m pytest && coverage report",
    "flake8 --max-line-length=88 .",
    "black --skip-string-normalization .",
    "isort --profile black .",
    "pre-commit install --install-hooks",
    "node -e 'console.log(1+1)'",
    "yarn add lucide-react clsx tailwind-merge",
    "npx tailwindcss init -p",
    "next build && next export",
    "prisma migrate dev --name init",
    "supabase login && supabase init",
    "stripe listen --forward-to localhost:4242/webhook",
    "ngrok http 8000",
    "docker exec -it container_id /bin/bash",
    "top -u user_name",
    "ps aux | grep node",
    "kill -9 $(lsof -t -i:3000)",
    "df -h /dev/sda1",
    "du -sh ./*",
    "ls -lahtr",
    "history | grep git",
    "whoami && hostname",
    "echo $PATH | tr ':' '\\n'",
    "ping -c 4 8.8.8.8",
    "dig +short example.com",
    "nslookup google.com",
    "ifconfig eth0",
    "netstat -tulnp",
    "iptables -L",
    "ufw status verbose",
    "fail2ban-client status",
    "openssl rand -base64 32",
    "base64 -d encoded_file.txt",
    "tar -czvf archive.tar.gz folder/",
    "unzip -l backup.zip",
    "find . -name '*.js' -type f",
    "locate config.json",
    "xargs -I {} cp {} backup/",
    "sed -i 's/old/new/g' file.txt",
    "awk '{print $1}' data.log",
    "vi ~/.zshrc",
    "nano /etc/hosts",
    "source ~/.bash_profile"
  ];

  return snippets.map((text, i) => ({
    id: `c-${i}`,
    title: `Code Snippet ${i + 1}`,
    difficulty: i < 30 ? 'Beginner' : i < 80 ? 'Intermediate' : 'Advanced',
    category: 'Coding',
    description: 'A vast collection of JS architecture, Python logic, and DevOps commands to master your keyboard.',
    text
  }));
};

const generateLiteratureLessons = (): Lesson[] => {
  const quotes = [
    "Call me Ishmael. Some years ago - never mind how long precisely - having little or no money in my purse.",
    "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness.",
    "Happy families are all alike; every unhappy family is unhappy in its own way.",
    "In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms.",
    "The sun did not shine. It was too wet to play. So we sat in the house. All that cold, cold, wet day.",
    "All children, except one, grow up. They soon know that they will grow up, and the way Wendy knew was this.",
    "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
    "The past is a foreign country; they do things differently there.",
    "Whether I shall turn out to be the hero of my own life, or whether that station will be held by anybody else.",
    "If you really want to hear about it, the first thing you will probably want to know is where I was born.",
    "It was a bright cold day in April, and the clocks were striking thirteen.",
    "Mr. and Mrs. Dursley, of number four, Privet Drive, were proud to say that they were perfectly normal.",
    "Far out in the uncharted backwaters of the unfashionable end of the western spiral arm of the Galaxy.",
    "I am an invisible man. No, I am not a spook like those who haunted Edgar Allan Poe.",
    "The sky above the port was the color of television, tuned to a dead channel.",
    "Once upon a time and a very good time it was there was a moocow coming down along the road.",
    "Life is to be lived, not controlled; and humanity is won by continuing to play in face of certain defeat.",
    "He was an old man who fished alone in a skiff in the Gulf Stream and he had gone eighty-four days.",
    "Mother died today. Or maybe, yesterday; I can't be sure. The telegram from the Home says: Mother deceased.",
    "Lolita, light of my life, fire of my loins. My sin, my soul. Lo-lee-ta: the tip of the tongue taking a trip.",
    "The cold passed reluctantly from the earth, and the retiring fogs revealed an army stretched out on the hills.",
    "True!—nervous—very, very dreadfully nervous I had been and am; but why will you say that I am mad?",
    "A screaming comes across the sky. It has happened before, but there is nothing to compare it to now.",
    "Deep into that darkness peering, long I stood there wondering, fearing, doubting, dreaming dreams no mortal ever dared to dream before.",
    "I have never begun a novel with more misgiving. If I call it a novel it is only because I don't know what else to call it.",
    "Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather on which a mirror and a razor lay crossed.",
    "Someone must have slandered Josef K., for one morning, without having done anything wrong, he was arrested.",
    "As Gregor Samsa awoke one morning from uneasy dreams he found himself transformed in his bed into a gigantic insect.",
    "It was the day my grandmother exploded. I sat in the crematorium, listening to the Reverend Mr. Gallow.",
    "I was born twice: first, as a baby girl, on a remarkably smogless Detroit day in January of 1960."
  ];

  return quotes.map((text, i) => ({
    id: `l-${i}`,
    title: `Literature Selection ${i + 1}`,
    difficulty: i < 10 ? 'Beginner' : i < 20 ? 'Intermediate' : 'Advanced',
    category: 'Literature',
    description: 'Excerpts from classic and modern literature.',
    text
  }));
};

export const INITIAL_LESSONS: Lesson[] = [
  ...generateStandardLessons(),
  ...generateCodingLessons(),
  ...generateLiteratureLessons()
];
